### ISSUE TITLE
How to made readonly date ranges

### ISSUE THREAD

**Issue by orney21d** [dangrossman/bootstrap-daterangepicker#1475]
Hi, i would like to have calendar, in read mode, for dates availabilities in a booking rooms, how can i configure datetimepicker for this purpose??. Thanks in advance.

**Comment by dangrossman** [comment]
This is a date picker not a date displayer. There are no options that will make it read only. You will have to do some coding of your own.

**Comment by ctf0** [comment]
for anyone still looking into that, a simpler solution could be

```js
selector.on('show.daterangepicker', function(ev, picker) {
    if (some_condition) {
        $('.daterangepicker').addClass('no-click')
    }
})
```

```css
.no-click {
    cursor: default !important;
    pointer-events: none !important;
}
```
