### ISSUE TITLE
Multiple radius redefinition

### ISSUE THREAD

**Issue by s1lver** [dangrossman/bootstrap-daterangepicker#1652]
Hi!

I ran into the problem of multiple `border-radius` redefinition in the project.

The radius is defined in several places, but I do not need it at all in the inroads.

1) Bootstrap sets the radius
2) My design theme resets the radius
3) The plugin sets the radius
4) The widget sets its radius !!!
5) And already I drop the radius again

WTF !!!

I believe that it is not necessary to pervert so much, and this is a very bad behavior.

The field has a `form-control` class and adding an additional `input-mini` class is not advisable.

My suggestion is to give the user a more flexible configuration. By the same plugin uses Bootstrap, so why add something to it?

```css
.datepicker {
    border-radius: 4px; //Remove radius. Used .dropdown-menu class
    direction: ltr;
}
```
