### ISSUE TITLE
Suggestion: in each month window show only days of that month

### ISSUE THREAD

**Issue by artknight** [dangrossman/bootstrap-daterangepicker#711]
Hi,
this is an idea that might give the range picker a better look. When a time span is selected, sometimes it shows on both months instead of just one. Attached in a screenshot of that. It does look a bit confusing, so I am suggesting in each month window to show only the days of that month. Hope this makes sense 
![screen shot 2015-07-16 at 10 53 47 am](https://cloud.githubusercontent.com/assets/157762/8726569/ffa4a370-2ba8-11e5-9c58-6da8b9fdf473.png)
:-)

**Comment by dangrossman** [comment]
Fixed this with just a CSS change, will be merged shortly

**Comment by artknight** [comment]
right on!

**Comment by artknight** [comment]
I see your change now. It is still a bit confusing to show the grayed out day numbers. It would be cleaner not to. Is that a quick fix? 

Check out my screenshot.
![screen shot 2015-07-16 at 11 44 07 am](https://cloud.githubusercontent.com/assets/157762/8727964/985413ba-2bb0-11e5-9f4b-3692770039fa.png)

**Comment by dangrossman** [comment]
I will not be removing the greyed out day numbers at this time. They are consistent with many other calendar widgets, including other date and date range pickers used with Bootstrap and jQuery, the Windows calendar, Google Calendar, etc.

**Comment by artknight** [comment]
For those of us who would like to do that, would you please provide a possible solution, maybe a CSS change perhaps?

**Comment by dangrossman** [comment]
`.daterangepicker td.off { color: #fff }`

**Comment by artknight** [comment]
Awesome, thank you!

**Comment by Poky85** [comment]
One note. Using `.off` class targets also days in current month that are before / after the minimum / maximum date.

**Comment by ctf0** [comment]
for anyone still searching for this, here u go

```scss
.daterangepicker {
  .drp-calendar td.available.off {
      cursor: default !important;
      opacity: 0; // hide other month days
      pointer-events: none !important;
  }

  // hide last row which is from next month
  .calendar-table table tbody tr:last-of-type {
      display: none;
  }
}
```
